micronaut:
  application:
    name: demo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/novo
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update